"""
retrain_from_db.py
==================
Extracts ALL events from the Sentinel database, labels them as normal
(per user instruction), generates synthetic attack contrast data, and
retrains the Random Forest classifier from scratch.

Usage:
    PYTHONPATH=src python3 scripts/retrain_from_db.py
"""

import sys
import asyncio
import sqlite3
import json
import zlib
import numpy as np
import pandas as pd
import pickle
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report
from sklearn.preprocessing import StandardScaler

BASE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE_DIR / "src"))

from common.config import DB_PATH
from common.feature_extractor import extract_features_from_eve, load_feature_names

MODELS_DIR = BASE_DIR / "models"
DATA_DIR = BASE_DIR / "data"
RANDOM_STATE = 42


async def extract_all_events():
    """Extract features from every event in the database, separating normal from simulated attacks."""
    db_path = DB_PATH
    if not Path(db_path).exists():
        print(f"[ERROR] Database not found: {db_path}")
        sys.exit(1)

    print(f"[INFO] Reading from: {db_path}")
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    rows = conn.execute(
        "SELECT raw_event, prediction FROM alerts ORDER BY timestamp DESC"
    ).fetchall()
    conn.close()

    print(f"[INFO] Found {len(rows)} total events in DB")

    feature_names = load_feature_names()
    all_normal = []
    all_attack = []
    skipped = 0

    for row in rows:
        raw_event_blob = row["raw_event"]
        if not raw_event_blob:
            skipped += 1
            continue
        try:
            decompressed = zlib.decompress(raw_event_blob).decode("utf-8")
            suricata_event = json.loads(decompressed)
            features = await extract_features_from_eve(suricata_event, feature_names)
            if features is None or all(v == 0.0 for v in features):
                skipped += 1
                continue
            
            # Check if event was generated by simulator (has 'features' key and is not None)
            if "features" in suricata_event and suricata_event["features"] is not None:
                all_attack.append(features)
            else:
                all_normal.append(features)
        except Exception:
            skipped += 1
            continue

    print(f"[INFO] Extracted normal: {len(all_normal)} | Extracted attack: {len(all_attack)} | Skipped: {skipped}")
    return all_normal, all_attack, feature_names



def generate_synthetic_attacks(X_normal: np.ndarray, n_attack: int, rng: np.random.Generator) -> np.ndarray:
    """
    Generate synthetic attack samples by perturbing normal traffic:
    - Amplify byte/packet counts (simulating DDoS/scan)
    - Distort timing features (simulating anomalous flows)
    - Add random noise beyond normal distribution bounds
    """
    n_features = X_normal.shape[1]
    attacks = []

    # Strategy 1: Extreme amplification of traffic features (40%)
    n1 = int(n_attack * 0.4)
    indices = rng.choice(len(X_normal), size=n1, replace=True)
    batch = X_normal[indices].copy()
    # Amplify packet/byte features (columns 1-4, 11-14) by 10-100x
    amplify_cols = [1, 2, 3, 4, 11, 12, 13, 14]
    for c in amplify_cols:
        if c < n_features:
            batch[:, c] *= rng.uniform(10, 100, size=n1)
    # Distort duration to very short (port scan) or very long
    if 0 < n_features:
        batch[:, 0] = rng.choice(
            [rng.uniform(0.01, 1.0, size=n1), rng.uniform(100000, 500000, size=n1)],
        )[0] if n1 > 0 else batch[:, 0]
    attacks.append(batch)

    # Strategy 2: Random outliers beyond normal bounds (30%)
    n2 = int(n_attack * 0.3)
    means = X_normal.mean(axis=0)
    stds = X_normal.std(axis=0) + 1e-6
    batch2 = means + stds * rng.uniform(3, 8, size=(n2, n_features))
    attacks.append(batch2)

    # Strategy 3: Zero-payload anomalies — unusual feature combos (30%)
    n3 = n_attack - n1 - n2
    indices3 = rng.choice(len(X_normal), size=n3, replace=True)
    batch3 = X_normal[indices3].copy()
    # Set bytes to 0 but packets high (suspicious empty-payload flood)
    for c in [3, 4, 13, 14]:  # byte columns
        if c < n_features:
            batch3[:, c] = 0.0
    for c in [1, 2, 11, 12]:  # packet columns
        if c < n_features:
            batch3[:, c] *= rng.uniform(50, 200, size=n3)
    attacks.append(batch3)

    return np.vstack(attacks).astype(np.float32)


async def main():
    print("=" * 70)
    print("  Sentinel Core — Full Model Retraining (DB Normal Baseline)")
    print("=" * 70)

    # ---- 1. Extract events from DB ----
    all_normal, all_attack, feature_names = await extract_all_events()

    # Supplement with local_normal.csv if it exists
    local_normal_path = DATA_DIR / "local_normal.csv"
    if local_normal_path.exists():
        try:
            df_local = pd.read_csv(local_normal_path)
            cols = [c for c in feature_names if c in df_local.columns]
            if len(cols) == len(feature_names):
                local_features = df_local[feature_names].values.tolist()
                all_normal.extend(local_features)
                print(f"[INFO] Loaded {len(local_features)} additional normal samples from {local_normal_path}")
            else:
                if len(df_local.columns) == len(feature_names):
                    local_features = df_local.values.tolist()
                    all_normal.extend(local_features)
                    print(f"[INFO] Loaded {len(local_features)} additional normal samples from {local_normal_path} (by column index)")
        except Exception as e:
            print(f"[WARN] Failed to load local_normal.csv: {e}")

    if len(all_normal) < 20:
        print("[ERROR] Too few normal samples for training (need >= 20).")
        sys.exit(1)

    X_normal = np.array(all_normal, dtype=np.float32)
    n_normal = len(X_normal)
    print(f"\n[INFO] Normal samples: {n_normal}")

    # ---- 2. Generate synthetic attack contrast data ----
    # Use ~30% attack ratio for balanced-ish training
    n_attack_synth = max(int(n_normal * 0.3), 50)
    rng = np.random.default_rng(RANDOM_STATE)
    X_synthetic = generate_synthetic_attacks(X_normal, n_attack_synth, rng)
    print(f"[INFO] Synthetic attack samples: {len(X_synthetic)}")

    # Combine with real simulated attacks from database if any exist
    if len(all_attack) > 0:
        X_attack_real = np.array(all_attack, dtype=np.float32)
        X_attack = np.vstack([X_attack_real, X_synthetic])
        print(f"[INFO] Real simulated attack samples: {len(X_attack_real)}")
    else:
        X_attack = X_synthetic
        print("[INFO] No real simulated attacks found in DB. Using synthetic only.")

    n_attack = len(X_attack)

    # ---- 3. Build dataset ----
    X = np.vstack([X_normal, X_attack])
    y = np.concatenate([np.zeros(n_normal), np.ones(n_attack)])
    print(f"[INFO] Total dataset: {len(X)} samples ({n_normal} normal + {n_attack} attack)")

    # Replace inf/nan
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

    # ---- 4. Train/test split ----
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
    )
    print(f"[INFO] Train: {len(X_train)} | Test: {len(X_test)}")

    # ---- 5. Fit scaler ----
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # ---- 6. Train Random Forest ----
    print("\n[INFO] Training Random Forest...")
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        max_features="sqrt",
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    model.fit(X_train_scaled, y_train)

    # ---- 7. Evaluate ----
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, model.predict_proba(X_test_scaled)[:, 1])

    print(f"\n{'=' * 50}")
    print(f"  Accuracy:  {accuracy * 100:.2f}%")
    print(f"  ROC-AUC:   {roc_auc:.4f}")
    print(f"{'=' * 50}")
    print(classification_report(y_test, y_pred, target_names=["Normal", "Attack"]))

    # ---- 8. Save artifacts ----
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    # Save model
    model_path = MODELS_DIR / "rf_model.pkl"
    with open(model_path, "wb") as f:
        pickle.dump(model, f)
    print(f"[OK] Saved: {model_path}")

    # Save scaler
    scaler_path = MODELS_DIR / "scaler.pkl"
    with open(scaler_path, "wb") as f:
        pickle.dump(scaler, f)
    print(f"[OK] Saved: {scaler_path}")

    # Save feature names
    features_path = MODELS_DIR / "features.json"
    with open(features_path, "w") as f:
        json.dump(feature_names, f, indent=2)
    print(f"[OK] Saved: {features_path}")

    # Save metrics
    metrics = {
        "accuracy": float(accuracy),
        "roc_auc": float(roc_auc),
        "train_samples": len(X_train),
        "test_samples": len(X_test),
        "num_features": len(feature_names),
        "class_distribution": {"normal": int(n_normal), "attack": int(len(X_attack))},
        "note": "Retrained from DB data — separated simulated attacks using features key, augmented with synthetic contrast and local normal data"
    }
    metrics_path = MODELS_DIR / "metrics.json"
    with open(metrics_path, "w") as f:
        json.dump(metrics, f, indent=2)
    print(f"[OK] Saved: {metrics_path}")

    # Save feature importance
    importance = pd.DataFrame({
        "feature": feature_names,
        "importance": model.feature_importances_
    }).sort_values(by="importance", ascending=False)
    importance_path = MODELS_DIR / "feature_importance.csv"
    importance.to_csv(importance_path, index=False)
    print(f"[OK] Saved: {importance_path}")

    # ---- 9. Recalibrate VAE threshold on newly scaled normal data ----
    print("\n[INFO] Recalibrating VAE threshold on pipeline-scaled normal data...")
    try:
        from ml_engine.vae_detector import VaeAnomalyDetector
        vae_enc = MODELS_DIR / "vae_encoder.keras"
        vae_dec = MODELS_DIR / "vae_decoder.keras"
        vae_scaler = MODELS_DIR / "vae_scaler.pkl"

        if vae_enc.exists() and vae_dec.exists() and vae_scaler.exists():
            detector = VaeAnomalyDetector(
                encoder_path=vae_enc, decoder_path=vae_dec,
                scaler_path=vae_scaler, threshold=0.3,
                feature_order=feature_names,
            )
            if detector.is_ready:
                X_normal_scaled = scaler.transform(X_normal).astype(np.float32)
                mse = detector.raw_mse(X_normal_scaled)
                p99 = float(np.percentile(mse, 99))
                new_vae_threshold = round(p99 * 1.1, 12)
                vae_cfg = {"threshold": new_vae_threshold, "input_dim": 22}
                vae_config_path = MODELS_DIR / "vae_config.json"
                with open(vae_config_path, "w") as f:
                    json.dump(vae_cfg, f)
                print(f"[OK] VAE threshold recalibrated: {new_vae_threshold:.6f}")
                print(f"[OK] Saved: {vae_config_path}")
            else:
                print("[WARN] VAE detector not ready — threshold not updated")
        else:
            print("[WARN] VAE model files missing — threshold not updated")
    except Exception as e:
        print(f"[WARN] VAE recalibration skipped: {e}")

    print(f"\n{'=' * 70}")
    print("  RETRAINING COMPLETE")
    print(f"  Model recognises your network traffic as NORMAL baseline.")
    print(f"  Restart the pipeline to load the new model.")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    asyncio.run(main())
